DROP TABLE IF EXISTS soldiers CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TYPE IF EXISTS position_commander CASCADE;
DROP TABLE IF EXISTS commanders CASCADE;
DROP TABLE IF EXISTS use_bullets CASCADE;
DROP TABLE IF EXISTS use_fuels CASCADE;